firebaseApiKey=AIzaSyDLipRuHcK054wc8OWcHxmM88MVJB7v9PU
firebaseApplicationId=1:170006710635:android:ea119140b45852aadaa42e
firebaseProjectId=classtracker-84920
firebaseStorageBucket=classtracker-84920.firebasestorage.app
firebaseSenderId=170006710635
googleWebClientId=170006710635-atlkuinjapndqjs4jsd3c1k6bkoiecrp.apps.googleusercontent.com
betaGoogleSignInConfigured=false
